sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t christiansb91/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true christiansb91/docker-react npm run test -- --coverage